[project]
name = "rdfc"
version = "0.1.0"
description = "Python runner for RDF-Connect using gRPC."
authors = [
    { name = "Jens Pots", email = "jens@jenspots.com" }
]
dependencies = [
    "grpcio>=1.65.4",
    "grpcio-tools>=1.65.4",
    "protobuf>=5.27.3",
    "types-protobuf>=5.27.0.20240626",
]
readme = "README.md"
requires-python = ">= 3.12"

[project.scripts]
"rdfc" = 'rdfc:main'

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/rdfc"]

[tool.hatch.envs.default]
type = "virtual"
path = ".venv"
system-packages = false
installer = "uv"

[tool.hatch.envs.default.scripts]
proto = "python -m grpc_tools.protoc --proto_path=../../proto --python_out=./src/rdfc/proto --pyi_out=./src/rdfc/proto --grpc_python_out=./src/rdfc/proto ../../proto/*.proto"
