PREFIX conn: <http://www.rdf-connect.com/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT
  ?key
  ?value

WHERE {
  ?processor a conn:Processor.
  ?processor ?key ?value.

  FILTER(?key != rdf:type)
  FILTER(?key != conn:target)
}
