PREFIX jvm: <https://w3id.org/conn/jvm#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX fno: <https://w3id.org/function/ontology#>
PREFIX fnom: <https://w3id.org/function/vocabulary/mapping#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT
  ?processor
  (group_concat(?key;separator=";") as ?keys)
  (group_concat(?value;separator=";") as ?values)

WHERE {
    ?processor a jvm:Processor.
    ?stage a ?processor.
    ?stage ?key ?value.
    FILTER (?key != "http://www.w3.org/1999/02/22-rdf-syntax-ns#type")
}

GROUP BY ?processor
