PREFIX jvm: <https://w3id.org/conn/jvm#>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX fno: <https://w3id.org/function/ontology#>
PREFIX fnom: <https://w3id.org/function/vocabulary/mapping#>

SELECT
  ?processor
  ?file
  ?class
  ?method
  ?language
  (GROUP_CONCAT(?name; separator=";") AS ?names)
  (GROUP_CONCAT(?index; separator=";") AS ?indices)

WHERE {
  ?processor
    a jvm:Processor ;
    jvm:file ?file ;
    jvm:class ?class ;
    jvm:method ?method ;
    jvm:language ?language ;
    jvm:mapping ?mappings .

  ?mapping
    a fno:Mapping ;
    fno:parameterMapping ?individualMapping .

  ?individualMapping
    a fnom:PositionParameterMapping ;
    fnom:implementationParameterPosition ?index ;
    fnom:functionParameter ?name .
}

GROUP BY ?processor ?file ?class ?method ?language ?mapping
