name: Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to GitHub Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/rdf-connect/orchestrator:latest ./orchestrator

      - name: Push the Docker image
        run: |
          docker push ghcr.io/rdf-connect/orchestrator:latest

